abinit/abipy

abipy/core/kpoints.py
This pull request automatically fixes all occurrences of the following issue:
Issue type: [Consider an iterator instead of materializing the list](https://www.quantifiedcode.com/app/issue_class/53lnAzfW)
Issue details: [https://www.quantifiedcode.com/app/project/gh:gmatteo:abipy?groups=code_patterns/%3A53lnAzfW](https://www.quantifiedcode.com/app/project/gh:gmatteo:abipy?groups=code_patterns/%3A53lnAzfW)
To adjust the commit message or the actual code changes, just [rebase](https://git-scm.com/docs/git-rebase) or [cherry-pick](https://git-scm.com/docs/git-cherry-pick) the commits.
For questions or feedback reach out to cody@quantifiedcode.com.
Legal note: We won't claim any copyrights on the code changes.
Cheers,
[Cody - Your code quality bot](https://www.quantifiedcode.com/cody)
=> Fix "Consider an iterator instead of materializing the list" issue

setup.py
When I try to install the package from source, I'm seeing:
```
Traceback (most recent call last):
File "setup.py", line 272, in <module>
cleanup()
File "setup.py", line 161, in cleanup
shutil.rmtree('abipy.egg-info')
File "/Users/Adam/spack/opt/spack/darwin-sierra-x86_64/clang-8.0.0-apple/python-2.7.13-hcpozzgaht7gddrvyrn2fprcm5tmqqii/lib/python2.7/shutil.py", line 239, in rmtree
onerror(os.listdir, path, sys.exc_info())
File "/Users/Adam/spack/opt/spack/darwin-sierra-x86_64/clang-8.0.0-apple/python-2.7.13-hcpozzgaht7gddrvyrn2fprcm5tmqqii/lib/python2.7/shutil.py", line 237, in rmtree
names = os.listdir(path)
OSError: [Errno 2] No such file or directory: 'abipy.egg-info'
```
This patch properly handles the `OSError` and allows me to build abipy successfully.
This patch is incorporated in …
=> Ignore OSError during build and installation

abipy/dfpt/ddb.py, abipy/dfpt/tests/test_ddb.py
The update_header function correctly builds the DDB file from the python dictionary for the AlAs_1qpt_DDB test.
The way the floating point is written in python and Fortran is different, so the test comparing directly the two lines does not work and was temporarily deactivated.
=> The update_header function in ddb.py passes the AlAs_1qpt_DDB test

abipy/flowtk/works.py, abipy/integration_tests/itest_relaxations.py
target_dilatmx was not updating the structure when restarting
=> fix target_dilatmx in relax workflow

abipy/dfpt/phonons.py
Annoying bug in acoustic_index. It was almost always returning [0,1,2], even when it was not supposed to.
=> fix bug in acoustic_index

abipy/core/kpoints.py, abipy/core/mixins.py, abipy/core/symmetries.py
There seems to be an import error due to changes in the pymatgen.util.serialization, where the SlotPickleMixin is now removed from the package. This will patch the error.
=> Fix SlotPickleMixin import error

abipy/dfpt/converters.py
Phonopy can store the unitcell/supercell/forceconstants/etc into a yaml file.
https://phonopy.github.io/phonopy/output-files.html#phonopy-yaml-and-phonopy-disp-yaml
Add the option to convert this file into ddb.
=> add option to convert from phonopy yaml file to ddb

abipy/gui/awx/dialogs.py
The `which` function of the `monty.os.path.which` module was deprecated some time ago. Here we replace it with the `shutil.which` function, which has been added since Python v3.3
=> Replace `monty.os.path.which` with `shutil.which`

abipy/tools/typing.py
=> Import from `typing` instead `pymatgen.util.typing`

abipy/flowtk/abitimer.py
Fixes #262 
In the following breaking change in `pymatgen`:
https://github.com/materialsproject/pymatgen/commit/5b88fc181d8ab97a7d1d3c47692cefdf673888c5
The `AbinitTimerParserError` class was renamed to `AbinitTimerParseError`. Although the code has already been updated for this change, in some environments installing `pymatgen>=2023.7.11` will lead to dependency conflicts. Here we adapt the import to be dependent on the installed version of `pymatgen` at runtime.
=> Fix `AbinitTimerParseError` import

abipy/core/fields.py
This is imported in `abipy.core.fields` which is automatically imported when `abipy` is imported and this can raise the error:
FileNotFoundError: [Errno 2] No such file or directory: '..pymatgen/io/vasp/potcar_summary_stats.json.gz'
The absence of this file should not make it impossible to merely import `abipy` and so the imports of `Poscar` and `Chgcar` are relegated to inside the scope where they are actually used.
=> Delay imports of `Poscar` and `Chgcar` of `pymatgen.io.vasp.outputs`

abipy/flowtk/flows.py, abipy/flowtk/qadapters.py
* Added a `try`/`except`  block for the two places this breaks abipy, [related pymatgen commit](https://github.com/materialsproject/pymatgen/commit/7da8d0a0b80e7ef0a554b506c78880de756f5e1d)
=> Backwards compatibility for deprecated pymatgen.core.units.Memory.from_string

abipy/dynamics/hist.py, abipy/electrons/lobster.py
On the CECI HPC abilab can take 34s to import with and without pre-compiled wheels, affecting performance of downstream high throughput studies.
After profiling this comes from the `abipy.dynamics.hist` and `abipy.electrons.lobster` header imports, specifically the `pymatgen.io.vasp.outputs.Vasprun`, `pymatgen.io.vasp.inputs.Potcar`, and `pymatgen.io.vasp.outputs.Xdatcar`. These pymatgen classes are exclusively used in read/write abipy class methods, so the import has been moved to the start of each method as a workaround.
Abilab now imports in about a second on my CECI environment
=> Import optimisation

abipy/abilab.py, abipy/core/kpoints.py, abipy/core/testing.py, abipy/flowtk/tasks.py, setup.py
pkg_resources is deprecated, and was used in abipy for the function parse_version.
Replace this function with packaging.version.parse.
=> Replace pkg_resources with packaging

abipy/dfpt/deformation_utils.py, abipy/dfpt/qha.py, abipy/dfpt/qha_aproximation.py
Some modification on qha.py
New file for  v-ZSISA-QHA approximation method ["Physical Review B 110 (1), 014103"]
New file for generating necessary deformation needed for ZSISA-QHA method
=> Some modification and new files for QHA

docs/links.rst, docs/workflows/taskmanager.rst
Replace dead link http://www.adaptivecomputing.com/products/open-source/torque/ with https://github.com/adaptivecomputing/torque.
Add a YAML resource to check the configuration file syntax.
=> Fix dead link and add resource to docs/workflows/taskmanager.rst

README.rst, abipy/core/structure.py
The number of digits for k-points printed with `abistruct.py kpath` was so low that some high-symmetry points went undetected with ` gsr.ebands.plot()`. The number of digits has been increased from 5 to 9. No modifications were made for the SIESTA output because performance for Siesta has not been tested.
See before (unconverged):
And after:
=> More digits for ABINIT paths with abistruct.py

abipy/dfpt/qha_2D.py, abipy/dfpt/qha_general_stress.py
The following updates have been made:
qha_2D.py
Added to compute ZSISA-QHA for systems with two degrees of freedom (2DOF).
Capable of calculating anisotropic thermal expansion and lattice constants for uniaxial configurations.
Requires PHDOS.nc and DDB files for GSR calculations or _GSR.nc files.
If PHDOS.nc is available for all structures, normal interpolation for QHA will be applied.
Supports the use of six PHDOS.nc files for specific structures to employ the E_infVib2​ approximation.
qha_general_stress.py
Computes thermal stress using EinfVib2EinfVib2​ for specific configurations across various crystallographic structures, from cubic to triclinic.
Please note that these files are not the final versions. I plan to discuss them further with Matteo.
=> scripts for ZSISA-QHA

abipy/eph/varpeq.py
Changes to Bqnu plotting
* Default scale: meV
* Default integration scheme for DOS: gaussian
* Color fill for BDOS
=> sync with abipy/develop

README.rst, docs/installation.rst
The README.rst and the documentation files now contain instructions to install AbiPy on a cluster that is accessible with the scp command, but from which one cannot access other online resources.
=> Instructions for offline install in README and docs

abipy/electrons/gwr.py
Correct the indexing in the GwrRobot class to properly access the ax_mat array in the get_dirgaps_dataframe method.
=> Fix indexing in GwrRobot for ax_mat access

abipy/dfpt/ddb.py
When invoking anaddb, DdbFile will update the default anaddb variables if epsilon info is present.
=> DdbFile triggers epsilon calculation in anaddb when needed
