abinit/abipy

abipy/electrons/__init__.py
abipy/electrons/ebands.py
abipy/htc/robots.py
abipy/lessons/lesson_Si_kpoint_convergence.py
abipy/lessons/lesson_template.py

refactoring bug fixes (edos ebands merge)
try execept on GSR parcing, not all calcualation are paw
fix to make local copy
a bit of color in the help of lesson one ..

lesson 1 now works

---

abipy/lessons/lesson_kpoint_convergence.py
abipy/lessons/lesson_relaxation.py

I need your opinions on the flow, so that I can go on with this lesson...

Relaxation of Si and GaN

---

abipy/lessons/lesson_dos_bands.py
abipy/lessons/lesson_ecut_convergence.py
abipy/lessons/lesson_helper_functions.py
abipy/lessons/lesson_kpoint_convergence.py
abipy/lessons/lesson_relaxation.py

could you merge again, the push did not finish ..

Bleedingedge

---

abipy/core/testing.py
abipy/data/runs/run_raman_optic.py

Test run_raman_optic is much lighter and faster
has_abinit takes an optional version argument, so that tests do not fail there !

Slight changes

---

abipy/abio/factories.py
abipy/abio/inputs.py
abipy/abio/tests/test_decorators.py
abipy/dfpt/ddb.py
abipy/dfpt/phonons.py
abipy/htc/abinitinput.py
abipy/htc/inputfile.py
abipy/htc/jobfile.py
abipy/htc/tests/test_jobfile.py
abipy/htc/variable.py
abipy/tools/decorators.py

This pull request automatically fixes all occurrences of the following issue:
Issue type: [Explicitly number replacement fields in a format string](https://www.quantifiedcode.com/app/issue_class/3aSZNLMu)
Issue details: [https://www.quantifiedcode.com/app/project/gh:gmatteo:abipy?groups=code_patterns/%3A3aSZNLMu](https://www.quantifiedcode.com/app/project/gh:gmatteo:abipy?groups=code_patterns/%3A3aSZNLMu)
To adjust the commit message or the actual code changes, just [rebase](https://git-scm.com/docs/git-rebase) or [cherry-pick](https://git-scm.com/docs/git-cherry-pick) the commits.
For questions or feedback reach out to cody@quantifiedcode.com.
Legal note: We won't claim any copyrights on the code changes.
Cheers,
[Cody - Your code quality bot](https://www.quantifiedcode.com/cody)

Fix "Explicitly number replacement fields in a format string" issue

---

abipy/htc/inputfile.py
docs/sphinxext/numpydoc.py

This pull request automatically fixes all occurrences of the following issue:
Issue type: [Avoid mutable default arguments](https://www.quantifiedcode.com/app/issue_class/3P0qV6OB)
Issue details: [https://www.quantifiedcode.com/app/project/gh:gmatteo:abipy?groups=code_patterns/%3A3P0qV6OB](https://www.quantifiedcode.com/app/project/gh:gmatteo:abipy?groups=code_patterns/%3A3P0qV6OB)
To adjust the commit message or the actual code changes, just [rebase](https://git-scm.com/docs/git-rebase) or [cherry-pick](https://git-scm.com/docs/git-cherry-pick) the commits.
For questions or feedback reach out to cody@quantifiedcode.com.
Legal note: We won't claim any copyrights on the code changes.
Cheers,
[Cody - Your code quality bot](https://www.quantifiedcode.com/cody)

Fix "Avoid mutable default arguments" issue

---

abipy/dfpt/ddb.py

Implemented a the update_header function to rewrite the header of the ddb file using the dictionary that was read previously.

Implemented a the update_header function to rewrite the ddb header

---

abipy/abio/inputs.py
abipy/abio/tests/test_inputs.py
abipy/dfpt/ddb.py

Fix for the dfpt input generator for anaddb.

fix dfpt anaddb input

---

abipy/dfpt/ddb.py
abipy/dfpt/tests/test_ddb.py
abipy/dfpt/tests/test_gruneisen.py
abipy/dfpt/tests/test_qha.py

* check for non zero components in DdbFile.has_bec_terms
* more robust instantiation of DielectricTensorGenerator
* increase tolerance for some tests

small updates for DdbFile

---

abipy/abio/outputs.py

Quick fix for loading output files where the cell is non-primitive

---

abipy/dfpt/converters.py

fix unit factor

---

abipy/core/func1d.py
abipy/dfpt/phonons.py
abipy/tools/plotting.py

*  Add ploty version(using Plotly’s Python graphing library) of ploty, ploty_with_phdos for phonon band, and ploty_harmonic_thermo, ploty for phonon DOS .
* Add helper functions for ploty.
* Fix yaxis.set_view_interval to set_ylim for matplotlib version of ploty_with_phdos for phonon band.

Add ploty version plot functions

---

abipy/dfpt/phonons.py
abipy/tools/plotting.py

* Add PhononBandsPlotter.combiplotly
* Update decorator and superscript string for plotly

Add PhononBandsPlotter.combiplotly 

---

abipy/core/abinit_units.py
abipy/core/func1d.py
abipy/dfpt/phonons.py
abipy/electrons/ebands.py
abipy/tools/plotting.py

Add ElectronBands.plotly
Add PhdosFile.plotly_pjdos_type

add phdos.plotly_pjdos_type and eband.plotly

---

abipy/dfpt/ddb.py
abipy/dfpt/phonons.py
abipy/dfpt/vsound.py
abipy/examples/plot/plot_phonons_infrared.py
abipy/examples/plot/plot_speed_of_sound.py
abipy/tools/plotting.py

* SoundVelocity.plotly
* DielectricTensorGenerator.plotly
* Some tiny corrections

add SoundVelocity.plotly and DielectricTensorGenerator.plotly

---

abipy/electrons/ebands.py
abipy/examples/plot/plot_ebands.py
abipy/examples/plot/plot_ebands_edos.py
abipy/examples/plot/plot_edos.py

* eband.plotly_with_edos
* In class ElectronDos
plotly
plotly_dos_idos
plotly_up_minus_down

plotly for ElectronDos and eband.plotly_with_edos

---

abipy/abio/inputs.py
abipy/core/testing.py
abipy/dfpt/ddb.py
abipy/dfpt/phonons.py
abipy/dfpt/raman.py
abipy/dfpt/tests/test_ddb.py

Generate Phonopy object along with phonon band structure

---

abipy/dfpt/phonons.py
abipy/dynamics/hist.py
abipy/electrons/ebands.py
abipy/examples/plot/plot_hist.py
abipy/examples/plot/plot_phonon_fatbands.py
abipy/tools/plotting.py

* add plotly_fatbands for PhononBands
* add plotly and plotly_traces for HistFile

add HistFile.plotly and PhononBands.plotly_fatbands

---

abipy/abio/abivar_database/variables_abinit.py
abipy/flowtk/utils.py
abipy/flowtk/works.py

Changes to allow cumulant expansion calculations. 
Adding POT and SIGEPH to deps. 
Adding abinit variable tolcum. 
Changing the nprocs when running eph_task 9.

Cumulant expansion

---

abipy/dfpt/phonons.py
abipy/electrons/ebands.py
abipy/electrons/fatbands.py
abipy/examples/plot/plot_efatbands.py
abipy/examples/plot/plot_efatbands_spin.py
abipy/examples/plot/plot_hist.py

* plotly_fatbands_typeview()
* plotly_fatbands_lview()
* plotly_pjdos_typeview()
* plotly_pjdos_lview()  
when stacked=False, the default x axis range is larger than matplotlib version.
* plotly_fatbands_with_pjdos()

plotly for FatBandsFile

---

abipy/dfpt/phonons.py
abipy/electrons/ebands.py
abipy/examples/plot/plot_ebands_grid.py

* Combiplotly and gridplotly for ElectronBands plotter
* Minor changes of combiplotly for PhononBandsPlotter

combiplotly and gridplotly for ElectronBands plotter

---

abipy/abio/inputs.py
abipy/abio/variable.py
abipy/eph/rta.py
abipy/flowtk/works.py

Small update on eph mobility

---

abipy/dfpt/phonons.py
abipy/electrons/ebands.py
abipy/examples/plot/plot_edos.py
abipy/examples/plot/plot_edos_grid.py
abipy/examples/plot/plot_phononDos_grid.py

* ElectronDosPlotter.combiplotly 
* ElectronDosPlotter.gridplotly
* PhononDosPlotter.gridplotly
* PhononDosPlotter.plotly_harmonic_thermo

Plotly functions for ElectronDosPlotter and PhononDosPlotter

---

abipy/abio/tests/test_factories.py
abipy/test_files/ion_ioncell_relax_ion_input.json
abipy/test_files/ion_ioncell_relax_ioncell_input.json

Added reference input json files for the ion and ioncell inputs generated by the ion_ioncell_relax_input factory method.
Added comparison test between the generated inputs and the reference files.

Update of ion_ioncell_relax_input unit test

---

abipy/abio/factories.py
abipy/abio/tests/test_factories.py
abipy/test_files/ion_ioncell_relax_ion_input.json
abipy/test_files/ion_ioncell_relax_ioncell_input.json

Refactored the ion_ioncell_relax_input factory function.
Behaves exactly the same way (the reference json inputs are the same).
@gmatteo : To be merged only when #246 is merged, hence draft pull request.

Ion ioncell relax input refactoring

---

abipy/abio/factories.py
abipy/abio/tests/test_factories.py
abipy/electrons/ebands.py
abipy/electrons/tests/test_ebands.py
abipy/test_files/ion_ioncell_relax_ion_input.json
abipy/test_files/ion_ioncell_relax_ioncell_input.json

Added factory functions for scr and sigma. Refactored g0w0_with_ppmodel_inputs using these.
Behaviour is the same as before.
Some changes may be decided here though (see comments in factory.py).
@gmatteo What do you think about this ?

Gw factory functions

---

abipy/abio/abivars.py
abipy/abio/tests/test_abivars.py

Added a method to compare AbinitInputFile objects, basically returning the differences between the two.
Unit tests added.

Added get_differences method for AbinitInputFile objects.

---

abipy/core/release.py
abipy/flowtk/wrappers.py

Reintroduce Python 3.8 support

---

abipy/abio/inputs.py

Added the case of ionmov=22 for AbinitInput.runlevel

Added ionmov=22 to the list of valid ionmov values

---

abipy/dfpt/deformation_utils.py
abipy/dfpt/qha.py
abipy/dfpt/qha_aproximation.py
abipy/dfpt/tests/test_qha.py

Thermal expansion can be calculated using the finite difference approach or a new, more accurate method.

small modification for QHA

---

abipy/abio/inputs.py

Fix silly bug in finding symmetry point group of a structure.

Fix atdep input

---

abipy/tools/plotting.py

Implement functionality to plot points in red if they converge within a specified range, enhancing visual differentiation in the plot.

Plot points with different colors based on convergence

---

abipy/electrons/gwr.py

Include the `gwr_max_hwtene` parameter.

Read gwr_max_hwtene from GwrFile

---

abipy/electrons/gw.py
abipy/electrons/gwr.py

Display tolerance information in title

Display tolerance information in title
